language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - sudo apt-get update
  - sudo apt-get install rpm
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm # make posix semaphores work for multiprocessing
install:
  - pip install pybuilder
  - pyb install_dependencies
script: "pyb"
